// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJYcqCp7uJV8gHsOSgKcV2d1cgeP9Hz8',
    appId: '1:442278246100:web:7f63e9c24e084906762d41',
    messagingSenderId: '442278246100',
    projectId: 'todo-authentication-c35d6',
    authDomain: 'todo-authentication-c35d6.firebaseapp.com',
    storageBucket: 'todo-authentication-c35d6.appspot.com',
    measurementId: 'G-3RZLL6DLQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBssR-ibC6b0s6P7c6TQUzY65KairM3viM',
    appId: '1:442278246100:android:ae323a8d91ff9fef762d41',
    messagingSenderId: '442278246100',
    projectId: 'todo-authentication-c35d6',
    storageBucket: 'todo-authentication-c35d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhNDv7ZetCZIJHpz1bg_bBz7SCzInAIw',
    appId: '1:442278246100:ios:befc334ec14ce6ee762d41',
    messagingSenderId: '442278246100',
    projectId: 'todo-authentication-c35d6',
    storageBucket: 'todo-authentication-c35d6.appspot.com',
    iosClientId: '442278246100-qopg6blgq0o39hhr49eoeig4dndlvp1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWhNDv7ZetCZIJHpz1bg_bBz7SCzInAIw',
    appId: '1:442278246100:ios:befc334ec14ce6ee762d41',
    messagingSenderId: '442278246100',
    projectId: 'todo-authentication-c35d6',
    storageBucket: 'todo-authentication-c35d6.appspot.com',
    iosClientId: '442278246100-qopg6blgq0o39hhr49eoeig4dndlvp1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationUi',
  );
}
